apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer-service-fullName" . }}
  labels:
    app: {{ include "producer-service-fullName" . }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: {{ include "producer-service-fullName" . }}
