advanced:
  image:
    repository: djarallahbrahim/jobstream-front
    tag: 0.0.4
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

  resources:
    limits:
      cpu: "500m"
      memory: "500Mi"
    requests:
      cpu: "250m"
      memory: "250Mi"

  env:
    MY_APP_API_BASE_URL: "http://producer-service:8080/job-offer-producer"

