apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer-service-fullName" . }}
  labels:
    app: {{ include "consumer-service-fullName" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ include "consumer-service-fullName" . }}
