apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-service-fullName" . }}-configmap
  labels:
    app: {{ include "front-service-fullName" . }}
data:
  MY_APP_API_BASE_URL: {{ .Values.advanced.env.MY_APP_API_BASE_URL }}
