apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-service-fullName" . }}
  labels:
    app: {{ include "front-service-fullName" . }}
spec:
  type: {{ .Values.advanced.service.type }}
  ports:
    - port: {{ .Values.advanced.service.port }}
      targetPort: {{ .Values.advanced.service.targetPort }}
  selector:
    app: {{ include "front-service-fullName" . }}
